log_level: info

username: needle
# password get from utils.security sha256_encode(your_password)
password: 3d58ae4c9423f50f324fedbf8c3c05818a72bcf74ca027072d07c3cf8e90aed0

ip: 0.0.0.0
port: 8471

origins:
  - http://localhost
  - http://localhost:8080
